version: "3.1"

services:
  sqldata:
    container_name: casa_marceneiro_db
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - ./restore:/restore
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      - SA_PASSWORD=191602fG*
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2GB"
        reservations:
          cpus: "2"
          memory: "2GB"
volumes:
  restore: {}
